dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0
  - OpenZeppelin/openzeppelin-contracts@4.3.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0'


networks:
  default: development
  development:
    keyhash: '0xcaf3c3727e033261d383b315559476f48034c13b18f8cafed4d871abe5049186'
    fee: 100000000000000000
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    host: http://127.0.0.1:8545
    chainid: 1337
  bnb-testnet:
    chainid: 97
    vrf_coordinator: '0xa555fC018435bef5A13C6c6870a9d4C11DEC329C'
    eth_usd_price_feed: '0x143db3ceEfbdfe5631aDD3E50f7614B6ba708BA7'
    link_token: '0x84b9B910527Ad5C03A9Ca831909E21e236EA7b06'
    keyhash: '0xcaf3c3727e033261d383b315559476f48034c13b18f8cafed4d871abe5049186'
    fee: 100000000000000000
    verify: False
    explorer:
      name: bscscan
      url: https://testnet.bscscan.com
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

api_keys:
  bscscan: ${BSCSCAN_API_KEY}